language: go

go:
  - 1.11.x

script:
  - go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)